# Generated by Django 4.2.13 on 2024-06-24 01:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('autor', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_obra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medium', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_genero',
        ),
        migrations.DeleteModel(
            name='Artista',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='obra',
            name='tipo_obra',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Myapp.tipo_obra'),
        ),
    ]
