# Generated by Django 4.2.13 on 2024-06-24 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0003_obra_tipo_obra_remove_cliente_id_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='imagen',
            field=models.ImageField(null=True, upload_to='productos'),
        ),
    ]
